import config from "@/config";

export const sidebarItems = [
  {
    title: "Dashboard",
    icon: config?.chart,
    iconActive: config?.home,
    path: "/",
    type: "link",
    submenu: [],
  },
  {
    title: "Project Managers",
    icon: config?.chart,
    iconActive: config?.home,
    category: "",
    path: "/Managers/List",
    submenu: [],
  },
  {
    title: "Projects",
    icon: config?.chart,
    iconActive: config?.home,
    path: "/Projects",
    type: "link",
    submenu: [],
  },
  {
    title: "Tasks",
    icon: config?.chart,
    iconActive: config?.home,
    path: "/Tasks/List",
    type: "link",
    submenu: [],
  },
  {
    title: "Shipment",
    icon: config?.chart,
    iconActive: config?.home,
    path: "/Shipment/Dashboard",
    type: "link",
    submenu: [],
  },
  {
    title: "QA/QC",
    icon: config?.chart,
    iconActive: config?.home,
    path: "/QA/QC",
    submenu: [],
  },
  {
    title: "FSEs",
    icon: config?.chart,
    iconActive: config?.home,
    category: "",
    path: "/FSEs",
    submenu: [],
  },
  {
    title: "Safety",
    icon: config?.chart,
    iconActive: config?.home,
    category: "",
    path: "/Safety",
    submenu: [],
  },
  {
    title: "Warehouse",
    icon: config?.chart,
    iconActive: config?.home,
    path: "/Warehouse/List",
    submenu: [],
  },
  {
    title: "Sales",
    icon: config?.chart,
    iconActive: config?.home,
    path: "/Sales/List",
    submenu: [],
  },
  {
    title: "Subscriptions",
    path: "/Subscriptions/List",
    icon: config?.chart,
    iconActive: config?.home,
    submenu: [],
  },
  {
    title: "Settings",
    path: "/Settings",
    icon: config?.chart,
    iconActive: config?.home,
    submenu: [],
  },
];
